web: gunicorn app:app --bind 0.0.0.0:$PORTLast login: Sun Aug  2 14:07:49 on ttys000
kunal@kunals-MacBook-Air ~ % curl -X POST https://inventory-management-system-production-702e.up.railway.app/api/login \ 
  -H "Content-Type: application/json" \
  -d '{"username":"testadmin","password":"placeholder_hash"}'
{"message":"Logged in","role":"Admin","username":"testadmin"}
kunal@kunals-MacBook-Air ~ % 















